spring.rabbitmq.host=warthog.lmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=lwozgcub
spring.rabbitmq.password=s3FjV7vS3b7kbZfpk_1z_RsqZF5EMtkO
spring.rabbitmq.virtual-host=lwozgcub
spring.rabbitmq.ssl.enabled=true